spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:flyway
    username: sam
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
server:
  port: 8091